spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/fang?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672


  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 1024
        max-idle: 200
        max-wait: -1s
mybatis:
  mapperLocations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.momo.seckill.pojo